[package]
name = "abc175"
version = "0.1.0"
authors = ["Ryohei Tsuda <lyohe@hey.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
